const fs = require('fs');
const path = './src/assets/docxContent.json';
const data = JSON.parse(fs.readFileSync(path, 'utf8'));
const oldStr = `<p><strong>5. Contact</strong></p><p><strong>Get in Touch with the Engineering Team.</strong></p><ul><li><strong>General &amp; Partnership Inquiries:</strong> For enterprise licensing, custom integrations, or general questions, reach out via our direct email desk or inquiry form.</li><li><strong>Security &amp; Vulnerability Disclosure:</strong> We take application security seriously. If you discover a potential vulnerability—such as an XSS vector in markdown previews or an IPC bridge privilege escalation—please report it immediately to our dedicated security response team for prioritized remediation.</li><li><strong>Community &amp; Feature Requests:</strong> Join our developer Discord or submit feature proposals directly through our verified GitHub issue trackers.</li></ul>`;
const newStr = `<p><strong>5. Contact</strong></p><p><strong>Direct Line to the Creator</strong></p><p>comπle is independently designed, architected, and built from the ground up by a sole developer. When you reach out, you aren't talking to a support desk—you are talking directly to the person who wrote the code.</p><ul><li><strong>General &amp; Partnership Inquiries:</strong> For enterprise licensing, custom integrations, or general architectural questions, reach out directly to my inbox.</li><li><strong>Security &amp; Vulnerability Disclosure:</strong> As the sole maintainer, I take application security seriously. If you discover a potential vulnerability—such as an XSS vector in markdown previews or an IPC bridge privilege escalation—please report it directly via email or open a private GitHub security advisory for prioritized remediation.</li><li><strong>Feature Requests &amp; Bug Reports:</strong> Have an idea for a new feature or found a bug? Submit an issue directly through the official GitHub repository.</li></ul><p><strong>Lead Architect &amp; Solo Maintainer</strong></p><p>Every line of code in comπle—from the Electron IPC bridges to the π-themed AI agents—was built by me. For technical collaborations or networking, let's connect:</p><ul><li><strong>GitHub:</strong> github.com/iamkartik0704</li><li><strong>Email:</strong> iamkartik0704@gmail.com</li><li><strong>LinkedIn:</strong> linkedin.com/in/kartik-chawla-189430203</li></ul>`;

data.footer_section = data.footer_section.replace(oldStr, newStr);
fs.writeFileSync(path, JSON.stringify(data, null, 2));
console.log("Updated contact info.");
